configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/swarms%2Fswarms-ff98aeb385363c96deadd16effd39ab4ee4fefc91ac575b8da42dfd4a2d0cc4e.yml
openapi_spec_hash: 424ea642424d31a4b0dca76e218b8c2a
config_hash: be8e2af934317a3e87d90d54fe55ccf8
